[package]
name = "rtmp-ingress"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "RTMP contribution ingress for Wavey media services"
repository = "https://github.com/wavey-ai/rtmp-ingress"

[features]
default = []

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
bytes = "1"
chrono = "0.4.38"
rml_rtmp = "0.8.0"
tracing = "0.1.40"
futures = "0.3.30"
xmpegts = "0.2.4"
boxer = { package = "wavey-boxer", version = "0.1.0" }
srt-tokio = "0.4.4"
tokio-stream = "0.1.15"
access-unit = "0.1.3"
gatekeeper = { package = "wavey-gatekeeper", version = "0.1.0" }
